name = "goplayproxy"
main = "build/worker/shim.mjs"
compatibility_date = "2025-01-12"

[build]
command = "cargo install -q worker-build && worker-build --release"

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.

[vars]
RUST_LOG = "info"
